// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessAudioBase64(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProcessAudioBase64'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAudioProcessing() {
  return window['go']['main']['App']['StopAudioProcessing']();
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
