// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ProcessAudioBase64(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function StopAudioProcessing():Promise<void>;

export function Test(arg1:string):Promise<string>;
