@startuml ERD
title __Диаграмма активности__

skinparam legendBackgroundColor white

legend
|= Цвет |= Значение|
|<#LightGrey>| Опциональный модуль|
endlegend

|Telegram-бот|
start
:(?) Получаем сообщение от пользователя;

|Бэкенд|
partition "Получение\nи обработка\nданных" {
  :(?) Парсим и обрабатываем документ;
  :Получаем монолитный текст;
}

|Кластеризатор|
partition "Разделение на\nсемантические\nфрагменты" {
  :Разделяем по предложениям;
  :Кластеризуем предложения;
  :Группируем по кластерам предложений;
}

partition #LightGrey "Ранжирование\nфрагментов" {
:Ранжируем полученные фрагменты;
:Отсекаем нерелевантные фрагменты\n(N% c конца отранжированного списка);
}

|#AntiqueWhite|Сервис распознавания|
repeat :Для каждого фрагмента;
  partition "Суммаризация\nфрагментов" {
    :Проводим суммаризацию;
    :Проводим экстракцию фактов;
    :Проводим экстракцию триплетов\n(для графа знаний);
  }
repeat while (есть следующий фрагмент)

:(?) Суммаризируем суммаризации;


|Telegram-бот|
:Возвращаем пользователю;

end
@enduml