@startuml
// Никита Глазков - lavender 
// Надеждая Колезнева - lightblue
// Леонид Касьян - bisque
@startmindmap
<style>
rootNode {
    BackgroundColor white
    LineThickness 2.0
    RoundCorner 0
    Shadowing 0.0
}

</style>

* Суммаризация\nразговоров
**[#lightyellow] Суммаризация\n<b>пост-фактум</b>

***[#lightyellow] Суммаризация\n<b>монологов</b>

****[#lightyellow] Длительность: до 30 секунд
*****[#lightblue] Синхронная транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов

****[#lightyellow] Длительность: от 30 секунд\nдо <u:red>4 часов [граница транскрибации</u>\n<u:red>или суммаризации за раз]</u>
*****[#lightblue] Асинхронная транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов
*****_ <u:red>TODO: уточнить границу по времени</u>

**** Длительность: более <u:red>4 часов</u>
*****_ <u:red>TODO: распланировать</u>

***[#lightyellow] Суммаризация\n<b>диалогов</b>\n(2 собеседника)

****[#lightyellow] Длительность: до 30 секунд
*****[#bisque] Зафиксированная диаризация (известно количество собеседников)
*****[#lightblue] Статическая транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов

****[#lightyellow] Длительность: от 30 секунд\nдо <u:red>4 часов [граница транскрибации</u>\n<u:red>или суммаризации за раз]</u>
*****[#bisque] Зафиксированная диаризация (известно количество собеседников)
*****[#lightblue] Асинхронная транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов

**** Длительность: более <u:red>4 часов</u>
*****_ <u:red>TODO: распланировать</u>

***[#lightyellow] Суммаризация\n<b>полилогов</b>\n(N собеседников)

****[#lightyellow] Длительность: до 30 секунд
*****[#bisque] Незафиксированная диаризация (количество собеседников неизвестно)
*****[#lightblue] Статическая транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов

****[#lightyellow] Длительность: от 30 секунд\nдо <u:red>4 часов [граница транскрибации</u>\n<u:red>или суммаризации за раз]</u>
*****[#bisque] Незафиксированная диаризация (количество собеседников неизвестно)
*****[#lightblue] Асинхронная транскрибация
*****[#lavender] Суммаризация
*****[#lavender] Экстракция фактов

**** Длительность: более <u:red>4 часов</u>
*****_ <u:red>TODO: распланировать</u>


** <b>Потоковая</b>\nсуммаризация

*[#lavender] Никита Глазков
*[#lightblue] Надежда Колезнева
*[#bisque] Леонид Касьян
@endmindmap
@enduml