# Generated by Django 3.2.9 on 2023-08-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20230809_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('telegram_msg_id', models.PositiveBigIntegerField(verbose_name='ID сообщения в Telegram')),
                ('input_text', models.TextField(verbose_name='Отправленный текст')),
                ('openai_summarized_text', models.TextField(blank=True, verbose_name='Текст суммаризации (OpenAI API)')),
                ('done', models.BooleanField(default=False, verbose_name='Задача по суммаризации завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь Telegram')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
