# Generated by Django 3.2.9 on 2023-08-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizationtask',
            options={'verbose_name': 'Задача суммаризации', 'verbose_name_plural': 'Задачи суммаризации'},
        ),
        migrations.RenameField(
            model_name='summarizationtask',
            old_name='telegram_msg_id',
            new_name='user_telegram_msg_id',
        ),
        migrations.AddField(
            model_name='summarizationtask',
            name='bot_telegram_msg_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='ID сообщения бота в Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarizationtask',
            name='last_queue_task_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
