# Generated by Django 3.2.9 on 2023-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0002_auto_20230810_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizationtask',
            name='bot_telegram_msg_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID сообщения бота в Telegram'),
        ),
    ]
