# Generated by Django 3.2.9 on 2023-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0003_alter_summarizationtask_bot_telegram_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizationtask',
            name='bot_telegram_msg_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID сообщения бота'),
        ),
        migrations.AlterField(
            model_name='summarizationtask',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Задача завершена'),
        ),
        migrations.AlterField(
            model_name='summarizationtask',
            name='user_telegram_msg_id',
            field=models.PositiveBigIntegerField(verbose_name='ID сообщения пользователя'),
        ),
    ]
