# Generated by Django 3.2.9 on 2023-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0004_auto_20230811_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizationtask',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Длительность (секунд)'),
        ),
        migrations.AddField(
            model_name='summarizationtask',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID файла'),
        ),
        migrations.AddField(
            model_name='summarizationtask',
            name='transcribed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Сообщение транскрибировано'),
        ),
        migrations.AddField(
            model_name='summarizationtask',
            name='voice_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL файла сообщения'),
        ),
        migrations.AlterField(
            model_name='summarizationtask',
            name='last_queue_task_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID главной задачи в очереди'),
        ),
    ]
