# Generated by Django 3.2.9 on 2023-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0005_auto_20230811_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizationtask',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность (секунд)'),
        ),
    ]
