# Generated by Django 3.2.9 on 2023-08-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230809_2241'),
        ('summarizations', '0006_alter_summarizationtask_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarizationtask',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='summarizationtask',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='summarizationtask',
            name='transcribed',
        ),
        migrations.RemoveField(
            model_name='summarizationtask',
            name='voice_path',
        ),
        migrations.AlterField(
            model_name='summarizationtask',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Задача завершена полностью'),
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('file_id', models.CharField(blank=True, max_length=255, verbose_name='ID файла')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (секунд)')),
                ('voice_path', models.CharField(blank=True, max_length=255, verbose_name='URL файла сообщения')),
                ('transcribed_text', models.TextField(blank=True, verbose_name='Транскрибированный текст')),
                ('transcribed', models.BooleanField(blank=True, default=False, verbose_name='Сообщение транскрибировано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Голосовое сообщение',
                'verbose_name_plural': 'Голосовые сообщения',
            },
        ),
    ]
