# Generated by Django 3.2.9 on 2023-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0008_voicemessage_user_telegram_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='bot_telegram_msg_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='ID сообщения бота'),
        ),
    ]
