# Generated by Django 3.2.9 on 2023-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0010_voicemessage_summarization_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizationtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача суммаризации', 'verbose_name_plural': 'Задачи суммаризации'},
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='S3_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь для S3 хранилища'),
        ),
    ]
