# Generated by Django 3.2.9 on 2023-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0011_auto_20230813_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='stt_operation_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID облачной операции'),
        ),
    ]
