# Generated by Django 3.2.9 on 2023-08-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0012_voicemessage_stt_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizationtask',
            name='openai_extracted_facts',
            field=models.TextField(blank=True, verbose_name='Извлечённый список фактов (OpenAI API)'),
        ),
    ]
