# Generated by Django 3.2.9 on 2023-08-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0013_summarizationtask_openai_extracted_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizationtask',
            name='openai_extracted_facts',
            field=models.TextField(blank=True, default='', verbose_name='Извлечённый список фактов (OpenAI API)'),
        ),
    ]
