# Generated by Django 3.2.9 on 2023-12-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0015_alter_summarizationtask_openai_extracted_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangchainSummarizationTask',
            fields=[
                ('summarizationtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summarizations.summarizationtask')),
            ],
            options={
                'verbose_name': 'Задача суммаризации [Langchain]',
                'verbose_name_plural': 'Задачи суммаризации [Langchain]',
                'ordering': ['-created_at'],
            },
            bases=('summarizations.summarizationtask',),
        ),
    ]
